In [102]:
import tensorflow as tf

In [103]:
## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

In [104]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W= tf.Variable(tf.random.normal((1,1), mean=0, stddev=1))
b= tf.Variable(tf.random.normal((1,1), mean=0, stddev=1))
print("W : ", W)
print("b : ", b)

W :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.27924946]], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-1.423028]], dtype=float32)>


In [106]:
for j in range(len(x_data)):
   ## data * weight 작성
    WX = tf.matmul([x_data[j]], W)  # x_data[j]와 W를 곱함

    ## bias add 작성
    y_hat = tf.add(WX, b)  # WX에 b를 더함

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

y_data: ,  [1.0] prediction :  tf.Tensor([[-1.1437786]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[-0.8645291]], shape=(1, 1), dtype=float32)
y_data: ,  [5.0] prediction :  tf.Tensor([[-0.5852796]], shape=(1, 1), dtype=float32)
y_data: ,  [7.0] prediction :  tf.Tensor([[-0.30603015]], shape=(1, 1), dtype=float32)
